// <auto-generated />
using AStar.Dev.OneDrive.Sync.Client.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.OneDrive.Sync.Client.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317224145_MoveToEntityConfiguration")]
    partial class MoveToEntityConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccentIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSyncedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastSyncedAt_Ticks");

                    b.Property<string>("LocalSyncPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("QuotaTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuotaUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.SyncConflictEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DetectedAt_Ticks");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LocalModified_Ticks");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RemoteModified_Ticks");

                    b.Property<long>("RemoteSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Resolution")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ResolvedAt_Ticks");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "State");

                    b.ToTable("SyncConflicts");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.SyncFolderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "FolderId")
                        .IsUnique();

                    b.ToTable("SyncFolders");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.SyncJobEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CompletedAt_Ticks");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("QueuedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QueuedAt_Ticks");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RemoteModified_Ticks");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "State");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.SyncConflictEntity", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Data.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.SyncFolderEntity", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Data.Entities.AccountEntity", "Account")
                        .WithMany("SyncFolders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.SyncJobEntity", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Data.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("SyncFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
