// <auto-generated />
using System;
using AStar.Dev.OneDrive.Sync.Client.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.OneDrive.Sync.Client.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316091342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccentIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuotaTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuotaUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.SyncFolderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "FolderId")
                        .IsUnique();

                    b.ToTable("SyncFolders");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.SyncFolderEntity", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Data.Entities.AccountEntity", "Account")
                        .WithMany("SyncFolders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("SyncFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
